---
name: idr0097-reicher-proteintag/screenA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Intron-targeting sgRNA
    clientname: Intron-targeting sgRNA
    include: yes

  - name: Sense Sequence
    clientname: Sense Sequence
    include: yes

  - name: Antisense Sequence
    clientname: Antisense Sequence
    include: yes

  - name: Has Phenotype
    clientname: Has Phenotype
    include: yes

  - name: Phenoptye Annotation Level
    clientname: Phenoptye Annotation Level
    include: yes

  - name: Phenotype 1
    clientname: Phenotype 1
    include: yes

  - name: Phenotype 2
    clientname: Phenotype 2
    include: yes

  - name: Phenotype 3
    clientname: Phenotype 3
    include: yes

  - name: Channels
    clientname: Channels
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
      - name: Characteristics [Cell Line]
        clientname: Cell Line
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Gene Identifier
        include: yes
      - name: Gene Identifier
        clientname: Gene Identifier URL
        clientvalue: >
          http://www.ensembl.org/id/{{ value|urlencode }}
        include: yes
      - name: Gene Symbol
        include: yes
        omitempty: no

  - group:
      namespace: openmicroscopy.org/mapr/gene/supplementary
      columns:
      - name: Gene Annotation Comments
        clientname: Gene Annotation Comments
        include: true

advanced:
  well_to_images: true
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line